theme: minima
title: Full Count
description: Houston Sports Analysis
author: Siddharth Nair
baseurl: "/Bullpen"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll-last-modified-at
  # - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive
  permalinks:
    category: /categories/:name/